channels:
  - conda-forge
  - default
dependencies:
  - django
  - djangorestframework
  - factory_boy
  # development
  - black
  - docker-compose
  - flake8
  - mypy
  - pip
  - pre-commit
  - pip:
    -  django-extensions
