version: '3'
services:

  djangopoc:
    image: djangopoc:${PYTHON_VERSION:-3.7}
    env_file:
      - ./.env
    volumes:
      - /tmp/djangopoc:/tmp
      - ..:/djangopoc
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.7}
